### ISSUE TITLE
Grammar still does not fit the JDL spec

### ISSUE THREAD

**Issue by colameo** [jbadeau/jdl#23]
...I'm changing this right now

**Comment by colameo** [comment]
fixed #22

**Comment by jbadeau** [comment]
Just curious? Was it just the ordered validators or did I miss more? Hopefully I can migrate the unit tests https://github.com/jbadeau/jdl/issues/3 this week. Prob best not to do an official release until we have decent coverage.

**Comment by colameo** [comment]
entity Job {
  jobId Long,
  jobTitle String minlength(5) maxlength(25),
...

this was not working, because the grammar expected always the keyword "required" before other validator keywords.

**Comment by deepu105** [comment]
Guys plz also note that the validations could be in any order

Thanks & regards,
Deepu

**Comment by colameo** [comment]
exactly, therefore it's now unordered (which means "any order" is allowed) ;-)
